### ISSUE TITLE
Astral Sorcery Floating Crystals stop working

### ISSUE THREAD

**Issue by Hjaldar** [xt9/cryogenic-simulation#1]
Due to the ongoing unfixed presence of https://github.com/HellFirePvP/AstralSorcery/issues/535, it may be worth flagging the fix (restart) in the guide, as it can effectively block progression if the player does not know how to fix it.

**Comment by xt9** [comment]
Since this issue wont be fixed on 1.12.2 I added a note about this in patchouli
