### ISSUE TITLE
[0.4.0] Inconsistent and problematic item hiding of TiC tool parts in JEI

### ISSUE THREAD

**Issue by Hjaldar** [xt9/cryogenic-simulation#10]
A large number of craftable TiC tool part material variants are hidden in JEI using \config\jei\itemBlacklist.cfg. This is currently done somewhat inconsistently (not done for all tool parts) and is problematic for TiC tool parts in particular, where each of the variants have different stats.

For example, TiC sword blades, large sword blades, hammer head and tough binding variants except for Soulium are all hidden in JEI. The other material variants of these tool parts are all still craftable and the stats of most of them can be checked by looking at uses of the Sword Blade Cast on the Crafting tab in JEI. However, sword blades, and other such items, made from the Sword Blade Pattern rather than by casting, e.g. Prismarine or Cactus tool parts, cannot have their stats checked and their is no way to know if they are craftable except by actually crafting them in a Part Builder. There is no JEI support for the Part Builder.

I think it is a good idea to remove as much JEI clutter as possible, so I'm not necessarily suggesting reverting this change. In fact, for consistency and to reduce clutter, other TiC tool part variants could also be hidden, provided an alternate method is available to check the stats of those (hidden) tool parts.  

Option 1: Provide an alternate method for discovering the stats of the hidden material variants. For example, add a tooltip to the Soulium Sword Blade (and other TiC tool parts) stating that one should look at uses of the Sword Blade Cast in JEI to find other material variants. I don't have a solution for those materials which use the Pattern rather than the Cast though. Then hide all material variants except Soulium for all other TiC tool parts as well (for consistency).

Option 2: Either through a tooltip or the Simulation Manual, alert the user to use Hide Ingredients Mode in JEI if they want to find hidden material variants of TiC tool parts.  Then hide all material variants except Soulium for all other TiC tool parts as well (for consistency).

Option 3: Unhide all TiC tool parts in JEI and only use item hiding for things like AE2 facades and cables, where the variants are identical except for appearance.

**Comment by xt9** [comment]
Yep this is just a mistake on my part that I didn't catch before v0.4, While hiding the fake iron tool parts I accidentally "wildcard" removed some of the parts, most of them _are_ meant to be displayed.
