### ISSUE TITLE
[0.4.0] Thermal Foundation Stone Shears

### ISSUE THREAD

**Issue by Hjaldar** [xt9/cryogenic-simulation#11]
These appear in JEI but have no recipe. Either add a recipe or hide in JEI.

**Comment by xt9** [comment]
Yeah I should remove the ContentTweaker stone shears I made early on in the pack and instead add the recipe to the TF stone shears, I've been intending to do this which is why they are displayed in JEI. Guess I forgot to add it to my TODO list though. Thanks for reminding me.

**Comment by xt9** [comment]
They disappeared on their own 👀
