### ISSUE TITLE
[0.4.0] (very minor issue) Add Traverse saplings as Furnace Fuels

### ISSUE THREAD

**Issue by Hjaldar** [xt9/cryogenic-simulation#12]
While collecting large quantities of Fir Wood to turn into Treated Wood Planks, I also collected many stacks of Fir Saplings. It would be nice if they (and potentially other Traverse saplings) could be used as an early game furnace fuel source, similar to vanilla saplings.

Suggestion: Add the following lines to \scripts\mods\traverse.zs:

`# Add traverse saplings as Furnace fuel`
`furnace.setFuel(<traverse:fir_sapling>, 100);`
`furnace.setFuel(<traverse:red_autumnal_sapling>, 100);`
`furnace.setFuel(<traverse:brown_autumnal_sapling>, 100);`
`furnace.setFuel(<traverse:orange_autumnal_sapling>, 100);`
`furnace.setFuel(<traverse:yellow_autumnal_sapling>, 100);`

**Comment by xt9** [comment]
Fixed in f940d27731133f4a6c6c96cfca72716e0f7bb6cb
