### ISSUE TITLE
[0.4.0] Original recipe for Astral Sorcery Luminous Crafting Table

### ISSUE THREAD

**Issue by Hjaldar** [xt9/cryogenic-simulation#14]
Something has changed in Astral Sorcery recently (AstralSorcery-1.12.2-1.10.15) and either the method you were using for disabling the Luminous Crafting Table recipe in 0.3.1 no longer works or those recipes are now shown in JEI when they weren't previously.

There is now this new version of the recipe in JEI:
![image](https://user-images.githubusercontent.com/3286136/58495392-bad60880-81ba-11e9-84ee-320da1d8d460.png)

This recipe can be removed from the game and the Astral Tome by setting 

`    B:LightProximity-Altar=false`

in \config\astralsorcery.cfg.

The recipe can probably also be removed using CraftTweaker but I am unsure whether doing so also removes the recipe from the Astral Tome.

**Comment by xt9** [comment]
Fixed in dev.
