### ISSUE TITLE
Glass Cutter

### ISSUE THREAD

**Issue by Noname500** [xt9/cryogenic-simulation#18]
Just a request for the glass cutter to be enabled

**Comment by xt9** [comment]
cant remember what this was about

**Comment by Noname500** [comment]
I wanted the glass cutter from extra utilities enabled so I could break glass and get it back

**Comment by N1K-x** [comment]
you could also use a silk touch pickaxe I think

**Comment by xt9** [comment]
Yeah you can use silk touch, I would rather the player use the vanilla behaviour than adding another item to the game
