### ISSUE TITLE
Arc Furnace - Recycling: potential for dupes, conversions

### ISSUE THREAD

**Issue by Hjaldar** [xt9/cryogenic-simulation#2]
Arc Furnace - Recycling outputs for Immersive Engineering items are based upon the original recipes, not the modified recipes. As a result, there is the potential for item duplication and/or conversion of one resource to another by use of a crafting/recycling loop.

Examples:
4 * Heavy Engineering Blocks require 2 steel to make, but return 8 on recycling (for the cost of some other materials)
8 * Redstone Wire Coil require 1 aluminium to make, and return 3 ingots and 5 nuggets on recycling (for the cost of two redstone and a treated stick)

There is no way to add/remove recycling recipes with crafttweaker. It is possible to completely disable arc furnace recycling in immersiveengineering.cfg.

Not sure the best solution to suggest here.

**Comment by xt9** [comment]
Disabled for now.
