### ISSUE TITLE
[0.4.0] Beginning of Arid Wastes feels very linear

### ISSUE THREAD

**Issue by Hjaldar** [xt9/cryogenic-simulation#21]
After some reflection I've come to agree with IterationFunk's view that the beginning of the Arid Waste simulation feels grindy. On thinking back, I spent most of that period in my base doing crafting, and then realising I needed to do more crafting because I'd run out of something. I don't think there is anything wrong with the actual progression, just with how much of it there is without a break. I think it is currently also a bit too linear, at least through the first 3 stages, up to the end of Plastic Production. I'd be curious what other testers think when they get to this point.

I think this situation could be improved considerably by adding an exploration component to the Arid Wastes. Currently, there is no incentive to explore this dimension as all the needed resources (Oil, Red Rock, Certus Ore) are available almost everywhere. Exactly how this is done could depend on the lore for this dimension: is it an untouched lifeless world which is rich in some resources or a barren, polluted wasteland where only a few resources remain? Are the oil oceans the result of an untouched past or were they originally water and came about due to unchecked pollution?

Some suggestions:
1) Add fog/smog/darkness to the dimension. Maybe even make the atmosphere poisonous (some sort of constant potion effect). Possibly even bring the Mekanism Gas Mask and Scuba Tank forward.
2) Move the scorpions to a special structure, a scorpion pit. Maybe only allow scorpions to spawn on a special block on the bottom of this pit. Sprinkle around some environmental hazards. This would also solve the issue of scorpions spawning in well-lit areas supposedly protected by a Mega Torch.
3) Add a very rare destroyed arcology/biodome type of structure where a few waterwheels and stone axles might be found. Maybe spread a few plants and some sludge or sewage around.
4) A very rare destroyed factory structure where an occasional refinery or thermopneumatic processing plant and some pressure tubes might be found. Maybe also some compressed iron blocks.
5) Have the rare structures have some sort of defensive mechanism which gets activated either on generation into the world or a player getting too close. Possibilities could include: hostile drones (TF elementals maybe) or other mobs (charged creepers + skeletons together?), active tnt or other triggered explosions.

**Comment by xt9** [comment]
Will add Oil Rigs as a rare structure in the Arid Waste, other than that I'm fine with the dimension being a bit less exciting than the lunar plane, its a wasteland after all.

Might have to take another look at microcrafting exhaustion in that simulation because we are getting autocrafting rather late in this pack.

**Comment by xt9** [comment]
(Hopefully better) in c826220ca4f50044a13b3b3e07a08c92c07f2a3b
