### ISSUE TITLE
[0.4.0] Can't craft chest out off Traverse Planks

### ISSUE THREAD

**Issue by athrane** [xt9/cryogenic-simulation#23]
Got the fir from traverse to make the treated wood but can't use it to make chests
Is there a reason for this or is it a oversight?

![image](https://user-images.githubusercontent.com/15695407/59555213-75358000-8faf-11e9-8678-c34442bb6388.png)

**Comment by xt9** [comment]
They're probably just missing from the oredict. Thanks for reporting
