### ISSUE TITLE
[0.4.0] Celestial Gateway (QoL)

### ISSUE THREAD

**Issue by N1K-x** [xt9/cryogenic-simulation#25]
This is no issue, it's a QoL thing.
Due to the fact the astral sorcery is more or less completely playable (chest plate isn't craftable until ender pearls) Celestial Gateways are possible to craft/build (one can teleport between different gateways) so they are an alternative to the way stones. While waystones need less space and are easier to obtain it costs experience to travel between great distances. My thought was to mention in the QoL chapter that for great distances a Celestial Gateway would be better.
On the other hand I'm not sure if it's worth it, because there is barely any need to travel between such great distances. (I personally only did this because I searched for a nicer spot to build my Astral Stuff)
You could also make Celestial Gateways more powerful or also less powerful by changing the xp cost of Waystone teleports (configure able in config file).

**Comment by xt9** [comment]
The patchouli guide would grow too large if I had to mention every single mod feature. Right now I only highlight/recommend certain item because they are needed and available in a certain context, this goes outside of that (and players will have access to that information through the AS guide)
