### ISSUE TITLE
[0.3] All Thermal Expansion Ores unbreakable

### ISSUE THREAD

**Issue by Hjaldar** [xt9/cryogenic-simulation#3]
My guess is that the following lines of block_properties.zs are responsible:

>var infusedManaDef = <thermalfoundation:ore:8>.asBlock().definition;
>infusedManaDef.setUnbreakable();

Quick fix for now to allow testing to continue is to comment out these lines. I will look for a more permanent fix.

**Comment by Hjaldar** [comment]
I think the issue is that all TE ores are different block states of thermalfoundation:ore.

print(infusedManaDef.id);
outputs
thermalfoundation:ore

And .setUnbreakable() sets all the block states to unbreakable.

**Comment by xt9** [comment]
Pickletweaks can also do blockhardness, and with oredict aswell. So maybe that's a good workaround
```   
 # Here you can override the hardness of blocks.
    # - Syntax: modid:blockid=hardness
    # - Example: minecraft:stone=100
    # You can also override using OreDictionary entries.
    # - Syntax: ore:orevalue=hardness
    # - Example: ore:oreCopper=25
    S:block_hardness <
     >
```

**Comment by xt9** [comment]
I think I'll just move Mithril to the IF laser so I don't have to spend a lot of time on figuring this one out.
