### ISSUE TITLE
[0.3.1] Ender Pearls from Astral Sorcery Shooting Stars

### ISSUE THREAD

**Issue by Hjaldar** [xt9/cryogenic-simulation#5]
Quite limited source of Ender Pearls, but still progression breaking I guess.

```
val astralShootingStarLootTable = LootTables.getTable("astralsorcery:shooting_star");
val astralShootingStarPool = astralShootingStarLootTable.getPool("astralsorcery:shooting_star");

astralShootingStarPool.removeEntry("minecraft:ender_pearl");
```

in /scripts/loot/astral_structures.zs to remove them. I have implemented and tested this fix.

It might be interesting to add other loot to these.

**Comment by xt9** [comment]
Fixed in dev
